/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.Calendar;
import Algorithms.WeatherForecaster;
import Algorithms.SimpleMovingAverage;
import Algorithms.DoubleMovingAverage;
import Algorithms.DoubleExponentialSmoothing;
import Algorithms.DoubleMovingAverage;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class InterfazInicial extends javax.swing.JDialog {

    private ArrayList<Double> lstDays = new ArrayList<Double>();
    private ArrayList<Double> lstForecaster = new ArrayList<Double>();

    /**
     * Creates new form InterfazInicial
     */
    public InterfazInicial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocation(500, 200);
        initComponents();
        renderOutput();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelValuestoForecast = new javax.swing.JLabel();
        labelWeatherReport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLast = new javax.swing.JTextArea();
        btnDeleteLast = new javax.swing.JButton();
        buttonAddReport = new javax.swing.JButton();
        txtForecast = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        btnForecast = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        labelWeatherReport1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        labelValuestoForecast1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelValuestoForecast.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelValuestoForecast.setText("Values to Forecast");

        labelWeatherReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelWeatherReport.setText("Weather Report");

        txtLast.setEditable(false);
        txtLast.setColumns(20);
        txtLast.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtLast.setRows(5);
        txtLast.setText("Current Data:");
        jScrollPane1.setViewportView(txtLast);

        btnDeleteLast.setText("Delete Last");
        btnDeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLastActionPerformed(evt);
            }
        });

        buttonAddReport.setText("Add");
        buttonAddReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddReportActionPerformed(evt);
            }
        });

        txtForecast.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtForecast.setText("1");
        txtForecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForecastActionPerformed(evt);
            }
        });

        txtValue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });

        btnForecast.setText("Forecast");
        btnForecast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForecastActionPerformed(evt);
            }
        });

        btnDeleteAll.setText("Delete All");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        labelWeatherReport1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelWeatherReport1.setText("Weather Forecast Application");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("°C");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("°F");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("°K");

        labelValuestoForecast1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelValuestoForecast1.setText("Unit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(labelWeatherReport1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnForecast))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWeatherReport)
                            .addComponent(labelValuestoForecast)
                            .addComponent(labelValuestoForecast1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtForecast)
                            .addComponent(txtValue)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAddReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteAll)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWeatherReport1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeatherReport)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValuestoForecast)
                    .addComponent(txtForecast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddReport)
                    .addComponent(btnDeleteLast)
                    .addComponent(btnDeleteAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(labelValuestoForecast1))
                .addGap(6, 6, 6)
                .addComponent(btnForecast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    private void txtForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForecastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForecastActionPerformed

    private void buttonAddReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddReportActionPerformed

        double value = Double.parseDouble(txtValue.getText());
        lstDays.add(value);
        txtValue.setText("");
        lstForecaster = new ArrayList<Double>();
        renderOutput();
    }//GEN-LAST:event_buttonAddReportActionPerformed

    private void btnForecastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForecastActionPerformed

        int days = Integer.parseInt(txtForecast.getText());
        Algorithms.WeatherForecaster weatherForecaster = new Algorithms.WeatherForecaster();
        lstForecaster = weatherForecaster.Get(lstDays, days);
        renderOutput();
    }//GEN-LAST:event_btnForecastActionPerformed

    private void btnDeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLastActionPerformed
        // TODO add your handling code here:
        lstDays.remove(lstDays.size()-1);
        renderOutput();
    }//GEN-LAST:event_btnDeleteLastActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
        for (int i = lstDays.size()-1; i >= 0; i--) {
            lstDays.remove(i);
        }
        renderOutput();
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void renderOutput() {
        Calendar fecha = Calendar.getInstance();
        String msg = "Current Date: " + fecha.get(Calendar.DATE)
                + "/" + (fecha.get(Calendar.MONTH) + 1)
                + "/" + fecha.get(Calendar.YEAR);

        //muestra las valores ingresados
        if (lstDays.size() > 0) {
            msg += "\n\n------------------------------------"
                    + "\n\nDias Anteriores \n";

            for (int i = 0; i < lstDays.size(); i++) {
                msg += lstDays.get(i) + "\n";
            }
        }

        //muestra el pronostico
        if (lstForecaster.size() > 0) {
            msg += "\n\n------------------------------------"
                    + "\n\nPronostico \n";

            for (int i = 0; i < lstForecaster.size(); i++) {
                msg += lstForecaster.get(i) + "\n";
            }
        }

        txtLast.setText(msg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazInicial dialog = new InterfazInicial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteLast;
    private javax.swing.JButton btnForecast;
    private javax.swing.JButton buttonAddReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelValuestoForecast;
    private javax.swing.JLabel labelValuestoForecast1;
    private javax.swing.JLabel labelWeatherReport;
    private javax.swing.JLabel labelWeatherReport1;
    private javax.swing.JTextField txtForecast;
    private javax.swing.JTextArea txtLast;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
